### PR TITLE
Add IBM MQ implementation

### PR DESCRIPTION
**Pull request by donovanmuller**
Besides the actual JMS binder implementation, this PR also contains:

* [build profiles](https://github.com/AbsaOSS/spring-cloud-stream-binder-jms#build-profiles) - probably a mute point once #7 is merged
* `JmsBinderConfigurationProperties` for global JMS binder configuration.
* `AnonymousNamingStrategy` to cater for apps with default settings (no consumer group defined).
* Allow e2e test implementations to override test methods.
* Parse JMS headers and replace illegal `-` characters in header names with `_`. Addresses #8.

### CODE REVIEW

**Comment by mbogoevici** [comment]
Thanks @donovanmuller  - this an excellent and welcome contribution, especially as we are gearing up towards the Chelsea release train of Spring Cloud Stream - since this hasn't been released yet, it's the best moment to bump up the dependency on SCSt to 1.2.0. 

This should be merged in conjunction with the separation of binders in individual repositories (as per #7). Once this is merged, we can continue with the work in https://github.com/spring-cloud/spring-cloud-stream/issues/745  - ensuring that the provisioning API is JMS-agnostic (which is another driver of having this dependent on SCSt 1.2.0).

I'll review and merge this and we can proceed with the next steps, I guess.

**Comment by mbogoevici** [comment]
@donovanmuller 
After a quick review of the changes, would it be possible to split this PR in two parts?

- one that would go against the common stuff in this repository containing all the core changes
- one that would be the implementation of the IBM MQ binder as a PR against the newly created https://github.com/spring-cloud/spring-cloud-stream-binder-ibm-mq

We are in the process of restructuring the JMS binders (already moved Solace) by keeping them in their own repositories so restructuring the PR would go a long way towards facilitating that. 

Thanks!

**Comment by donovanmuller** [comment]
@mbogoevici No problem  👍

**Comment by donovanmuller** [comment]
https://github.com/spring-cloud/spring-cloud-stream-binder-jms/pull/9/commits/7773e0b9e9b5836fe7d9908b350787ba941e79ba is in preparation for the split to the [spring-cloud-stream-binder-ibm-mq](https://github.com/spring-cloud/spring-cloud-stream-binder-ibm-mq) repo

**Comment by donovanmuller** [comment]
Closing this PR to make way for separate PR's as per  https://github.com/spring-cloud/spring-cloud-stream-binder-jms/pull/9#issuecomment-269007631

**Pull request closed without merging**
