### PR TITLE
Add DLQ name as a consumer property

### LINKED ISSUE #21: Make the DLQ name a consumer and not as binder property

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- Remove existing BinderConfiguration property
 - Use `dlqName` as the extended consumer property
  - Make JmsMessageChannelBinder to use extended consumer/producer properties
 - Update the binder and tests with the related changes

Resolves #21

### CODE REVIEW

**Comment by mbogoevici** [comment]
Made an additional change to make this easier to use with other binders https://github.com/mbogoevici/spring-cloud-stream-binder-jms/commit/5475e1280552e7c46c32b646d837e31098ac4aba

Added https://github.com/spring-cloud/spring-cloud-stream-binder-ibm-mq/pull/4 as a PR for IBM MQ to match the changes here.

I have some misgivings about creating an empty class for `JmsProducerProperties` but I guess that's required by `ExtendedPropertiesBinder`.

**Comment by mbogoevici** [comment]
Other than that this is ready to merge I suppose.

**Comment by donovanmuller** [comment]
@mbogoevici 👍 happy from my side

**Comment by ilayaperumalg** [comment]
> Made an additional change to make this easier to use with other binders mbogoevici@5475e12

👍

> I have some misgivings about creating an empty class for JmsProducerProperties but I guess that's required by ExtendedPropertiesBinder.

yeah, I felt the same when adding the empty `ProducerProperties` :-)

**Comment by mbogoevici** [comment]
Merged via https://github.com/spring-cloud/spring-cloud-stream-binder-jms/commit/cde5e0a07d114c15917e355b5cf982e274267b4c

**Pull request closed without merging**
